language: ruby
sudo: false
# Travis Ruby 1.9.3 stack is defaulting to version 1.7.6 of bundler
# which is incompatible with the Rubygems 2.6.13 security release.
#
# TODO: Remove when Travis updates its default:
#   https://github.com/travis-ci/travis-ci/issues/8357
before_install:
  - gem install bundler --version 1.15.4
bundler_args: --without development
script: "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=spec"
  - "CHECK=commits"

matrix:
  exclude:
    - rvm: 2.3.0
      env: "CHECK=commits"
    - rvm: 2.2.4
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
